# Default Activiti Audit Producer configuration values
spring.cloud.stream.bindings.auditProducer.destination=${ACT_RB_AUDIT_PRODUCER_DEST:engineEvents}
spring.cloud.stream.bindings.auditProducer.contentType=${ACT_RB_AUDIT_PRODUCER_CONTENT_TYPE:application/json}

#ensures the consumer (query, audit) will receive the message even if it starts after the message has been sent
spring.cloud.stream.bindings.auditProducer.producer.required-groups=${activiti.cloud.runtime-bundle.messaging.required-audit-producer-groups}

# overrides required audit producer groups when function router is used by query
activiti.cloud.runtime-bundle.messaging.required-audit-producer-groups=${ACT_QUERY_CONSUMER_GROUP:query},${ACT_AUDIT_CONSUMER_GROUP:audit}
spring.cloud.stream.rabbit.bindings.auditProducer.producer.queue-name-group-only=${activiti.cloud.messaging.function-router.enabled:false}
