version: 2
updates:
  - package-ecosystem: "maven"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.activiti:*"
      - dependency-name: "org.assertj:assertj-core"
        versions:
          - ">= 4"
      # Security update for Netty 4.1.x, remove with Spring Boot upgrade
      - dependency-name: "io.netty:*"
        versions:
          - ">= 4.2"

  - package-ecosystem: "github-actions"
    directories:
    - "/"
    - "/.github/actions/*"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
