version: 2
updates:
  - package-ecosystem: "maven"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.activiti:*"

  - package-ecosystem: "github-actions"
    directories:
    - "/"
    - "/.github/actions/*"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
