spring.cloud.stream.bindings.countConsumer.destination=${ACT_QUERY_COUNTS_DEST:pushedCounts}
spring.cloud.stream.bindings.countConsumer.contentType=${ACT_QUERY_COUNTS_CONTENT_TYPE:application/json}
spring.cloud.stream.bindings.pushedCountsRegistryProducer.destination=${ACT_QUERY_SUBSCRIBER_REGISTRY_DEST:subscriberRegistry}
spring.cloud.stream.bindings.pushedCountsRegistryProducer.contentType=${ACT_QUERY_SUBSCRIBER_REGISTRY_CONTENT_TYPE:application/json}
spring.cloud.stream.bindings.subscriberRegistryResyncConsumer.destination=${ACT_QUERY_SUBSCRIBER_REGISTRY_DEST:subscriberRegistry}
spring.cloud.stream.bindings.subscriberRegistryResyncConsumer.contentType=${ACT_QUERY_SUBSCRIBER_REGISTRY_CONTENT_TYPE:application/json}
