pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - author=alfresco-build-user
      - status-success=build
      - status-success=test (rabbitmq, partitioned)
      - status-success=test (rabbitmq, non-partitioned)
      - status-success=test (kafka, partitioned)
      - status-success=test (kafka, non-partitioned)
      - status-success=promote
      - label!=do-not-merge
    actions:
      merge:
        method: squash
        strict: true
  - name: automatic merge when CI passes and all requested reviews approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - status-success=build
      - status-success=test (rabbitmq, partitioned)
      - status-success=test (rabbitmq, non-partitioned)
      - status-success=test (kafka, partitioned)
      - status-success=test (kafka, non-partitioned)
      - status-success=promote
      - status-success=license/cla
      - label!=do-not-merge
    actions:
      merge:
        method: squash
        strict: true
