repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
        exclude: ^.*invalid.*\.json$
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.3.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types: [java]
        additional_dependencies:
          - prettier@2.5.1
          - prettier-plugin-java@1.6.1
