repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
        exclude: ^.*invalid.*\.json$
      - id: check-xml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types_or:
          - java
          - markdown
        additional_dependencies:
          - prettier@2.7.1
          - prettier-plugin-java@1.4.0
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.23.0
    hooks:
      - id: semgrep
        types: [java]
        args: ["--config", ".sempgrep.yaml", "--error","--metrics=off"]
