repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-json
        exclude: ^.*invalid.*\.json$
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.14.0
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        alias: check-dependabot
        name: "Validate Dependabot Config"
        files: '.github/dependabot\.yml$'
        args: ["--schemafile", "https://json.schemastore.org/dependabot-2.0.json"]
