github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-service-common
      branch: develop
    - name: activiti-cloud-connectors
      branch: develop
    - name: activiti-cloud-query-service
      branch: develop
    - name: activiti-cloud-org-service
      branch: develop
    - name: activiti-cloud-runtime-bundle-service
      branch: develop
    - name: activiti-cloud-audit-service
      branch: develop
    - name: activiti-cloud-api
      branch: develop
    - name: activiti-cloud-process-model-service
      branch: develop
    - name: activiti-cloud-app-service
      branch: develop
    - name: activiti-cloud-dependencies
      branch: develop
      useSinglePullRequest: true
