github:
  organisations:
  - name: activiti
    repositories:
    - name: ttc-connectors-reward
      branch: master
    - name: ttc-campaigns-service
      branch: master
    - name: ttc-acceptance-tests
      branch: master
    - name: ttc-rb-english-campaign
      branch: master
    - name: ttc-query-campaign
      branch: master
    - name: ttc-connectors-dummytwitter
      branch: master
    - name: ttc-connectors-ranking
      branch: master
    - name: ttc-connectors-processing
      branch: master
    - name: example-runtime-bundle
      branch: master
    - name: activiti-cloud-acceptance-scenarios
      branch: master
      useSinglePullRequest: true
    - name: example-cloud-connector
      branch: master
    - name: activiti-cloud-modeling
      branch: master
    - name: activiti-cloud-query
      branch: master
    - name: activiti-cloud-audit
      branch: master
    - name: activiti-cloud-notifications-graphql
      branch: master
