github:
  organisations:
    - name: activiti
      repositories:
        - name: activiti-cloud-acceptance-scenarios
          branch: master
          useSinglePullRequest: true
        - name: activiti-cloud-dependencies
          branch: develop
          useSinglePullRequest: true
        - name: activiti-cloud-audit
          branch: master
          useSinglePullRequest: true
        - name: example-cloud-connector
          branch: master
          useSinglePullRequest: true
        - name: example-runtime-bundle
          branch: master
          useSinglePullRequest: true
        - name: activiti-cloud-modeling
          branch: master
          useSinglePullRequest: true
        - name: activiti-cloud-query
          useSinglePullRequest: true
          branch: master
        - name: example-runtime-bundle
          branch: master
          useSinglePullRequest: true
