github:
  organisations:
    - name: alfresco
      repositories:
        - name: alfresco-process
          branch: develop
          useSinglePullRequest: true
        - name: alfresco-process-application-oracle-kafka
          useSinglePullRequest: true
