github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-acceptance-scenarios
      branch: develop
      useSinglePullRequest: true      
    - name: activiti-cloud-org-service
      branch: develop
      useSinglePullRequest: true
