github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-notifications-graphql
      useSinglePullRequest: true
  - name: alfresco
    repositories:
    - name: alfresco-process-oracle-kafka-application
      useSinglePullRequest: true
      
