github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-audit
      branch: master
      useSinglePullRequest: true
  - name: alfresco
    repositories:
    - name: alfresco-process-oracle-kafka-application
      useSinglePullRequest: true
