github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-dependencies
      branch: develop
      useSinglePullRequest: true
  - name: alfresco
    repositories:
    - name: alfresco-process-oracle-kafka-application
      useSinglePullRequest: true
