github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-query-service
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-runtime-bundle-service
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-audit-service
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-dependencies
      branch: develop  
      useSinglePullRequest: true
    - name: activiti-cloud-modeling-service
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-connectors
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-messages-service
      branch: develop
      useSinglePullRequest: true
