github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-query
      branch: develop
      useSinglePullRequest: true
    - name: activiti-cloud-notifications-service-graphql
      branch: develop
      useSinglePullRequest: true
