github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-full-chart
      branch: master
      useSinglePullRequest: true
  - name: alfresco
    repositories:
    - name: alfresco-process-parent
      useSinglePullRequest: true
    - name: alfresco-process-oracle-kafka-application
      useSinglePullRequest: true
    - name: alfresco-process-application-deployment
      useSinglePullRequest: true
