github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-query
      useSinglePullRequest: true
      branch: master
    - name: activiti-cloud-notifications-service-graphql
      branch: develop
      useSinglePullRequest: true
  - name: alfresco
    repositories:
    - name: alfresco-process-oracle-kafka-application
      useSinglePullRequest: true
