apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/activiti/activiti-cloud-acceptance-scenarios:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/activiti/activiti-cloud-acceptance-scenarios:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: activiti-cloud-acceptance-scenarios
        chartPath: charts/activiti-cloud-acceptance-scenarios
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/activiti/activiti-cloud-acceptance-scenarios"
          image.tag: "{{.DIGEST_HEX}}"
