spring.cloud.stream.bindings.pushedCountsQueryEventsConsumer.destination=${ACT_QUERY_EVENTS_DEST:queryEvents}
spring.cloud.stream.bindings.pushedCountsQueryEventsConsumer.contentType=${ACT_QUERY_EVENTS_CONTENT_TYPE:application/json}
