name: Run Playwright acceptance tests
description: Executes Playwright acceptance test.
inputs:
  working-directory:
    required: false
    description: The directory from which to run tests
    default: "."
  script-command:
    description: The npm command to execute playwright tests
    required: true

outputs:
  outcome:
    description: Tests outcome ('success', 'failure',...)
    value: ${{ steps.launch-tests.outcome }}
  message:
    description: Message for notification
    value: ${{ steps.rp-summarize.outputs.teams-message }}

runs:
  using: composite
  steps:

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '22'

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Setup cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@9f51752cb7845dce8e8b13b866c127681f418bb3 # v17.7.0

    - name: Add GitHub Step Summary
      shell: bash
      env:
        SCRIPT_COMMAND: ${{ inputs.script-command }}
      run: |
        echo "#### ⏱ Before Playwright Tests: $(date -u +'%Y-%m-%d %H:%M:%S%:z')" >> $GITHUB_STEP_SUMMARY
        echo "#### ⚙ Configuration" >> $GITHUB_STEP_SUMMARY
        echo "- Script command: ${SCRIPT_COMMAND}" >> $GITHUB_STEP_SUMMARY

    - name: Run Tests (continue on error)
      id: launch-tests
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
      env:
        SCRIPT_COMMAND: ${{ inputs.script-command }}
      run: |
        npm ci --ignore-scripts
        ./node_modules/.bin/playwright install chromium
        eval "${SCRIPT_COMMAND}"
      continue-on-error: true

    - name: Update GitHub Step Summary
      shell: bash
      run: |
        echo "#### ⏱ After Playwright Tests: $(date -u +'%Y-%m-%d %H:%M:%S%:z')" >> $GITHUB_STEP_SUMMARY

    - name: Exit on failure
      if: steps.launch-tests.outcome != 'success'
      shell: bash
      run: |
        echo "::error title=run-playwright-tests::Tests failed: re-throwing on error."
        exit 1
