name: "check-service-health"
description: "Check Services Health"
inputs:
  health-url:
    description: the health URL to be checked
    required: true
  max-attempts:
    description: The maximum number of attempts while calling health checks
    required: false
    default: "50"
  poll-interval:
    description: The poll interval in seconds between two attempts
    required: false
    default: "5"

runs:
  using: "composite"
  steps:
    - name: Check Service Health
      env:
        HEALTH_URL: ${{ inputs.health-url }}
        MAX_ATTEMPTS: ${{ inputs.max-attempts }}
        POLL_INTERVAL: ${{ inputs.poll-interval }}
      shell: bash
      run: bash "${GITHUB_WORKSPACE}/scripts/ci/check-service-health.sh"
