name: Setup environment
description: Setup environment to execute tests using specific message broker
inputs:
  messaging-broker:
    description: the name of the messaging broker
    required: true
  messaging-partitioning-option:
    description: the partitioning option to be used, i.e. `partitioned` or `non-partitioned`
    required: true
  messaging-destinations-option:
    description: the destinations option to be used, i.e. `default-destination` or `override-destinations`
    required: true
  version:
    description: the version being tested
    required: true

runs:
  using: composite
  steps:
    - name: Setup environment for ${{ inputs.messaging-broker }}
      env:
        MESSAGING_BROKER: ${{ inputs.messaging-broker }}
        MESSAGING_PARTITIONED: ${{ inputs.messaging-partitioning-option }}
        MESSAGING_DESTINATIONS: ${{ inputs.messaging-destinations-option }}
        VERSION: ${{ inputs.version }}
      shell: bash
      run: bash "${GITHUB_WORKSPACE}/scripts/ci/setup-matrix-env.sh"
