activiti.cloud.messaging.function-router.routes.auditConsumer.enabled=${ACT_AUDIT_CONSUMER_FUNCTION_ROUTER_ENABLED:false}

spring.cloud.stream.bindings.auditConsumer.consumer.partitioned=${activiti.cloud.messaging.partitioned}
spring.cloud.stream.bindings.auditConsumer.consumer.concurrency=${ACT_QUERY_CONSUMER_CONCURRENCY:1}

spring.cloud.stream.rabbit.bindings.auditConsumer.consumer.prefetch=${ACT_QUERY_CONSUMER_RABBIT_PREFETCH:20}

spring.cloud.stream.instanceIndex=${activiti.cloud.messaging.instance-index}
spring.cloud.stream.instanceCount=${activiti.cloud.messaging.partition-count}
spring.cloud.stream.bindings.auditConsumer.consumer.instanceIndexList=${ACT_AUDIT_CONSUMER_INSTANCE_INDEX_LIST:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}
