spring.application.name=${ACT_QUERY_APP_NAME:query-consumer}

spring.cloud.stream.bindings.queryConsumer.destination=${ACT_QUERY_CONSUMER_DEST:engineEvents}
spring.cloud.stream.bindings.queryConsumer.group=${ACT_QUERY_CONSUMER_GROUP:query}
spring.cloud.stream.bindings.queryConsumer.contentType=${ACT_QUERY_CONSUMER_CONTENT_TYPE:application/json}

# AUDIT
spring.cloud.stream.bindings.auditConsumer.destination=${ACT_AUDIT_CONSUMER_DEST:engineEvents}
spring.cloud.stream.bindings.auditConsumer.group=${ACT_AUDIT_CONSUMER_GROUP:audit}
spring.cloud.stream.bindings.auditConsumer.contentType=${ACT_AUDIT_CONSUMER_CONTENT_TYPE:application/json}

# AUDIT INCIDENTS
spring.cloud.stream.bindings.auditConsumerIncidents.destination=${ACT_AUDIT_CONSUMER_INCIDENTS_DEST:engineEventsIncidents}
spring.cloud.stream.bindings.auditConsumerIncidents.group=${ACT_AUDIT_CONSUMER_INCIDENTS_GROUP:auditIncidents}
spring.cloud.stream.bindings.auditConsumerIncidents.contentType=${ACT_AUDIT_CONSUMER_INCIDENTS_CONTENT_TYPE:application/json}
