spring.sleuth.integration.patterns=!hystrixStreamOutput*,!channel*,!clientInboundChannel*,!clientOutboundChannel*,!brokerChannel*,*

spring.graphql.websocket.path=/v2/ws/graphql
spring.graphql.websocket.keep-alive=PT5S

spring.graphql.cors.allowed-origin-patterns=${GRAPHQL_WS_CORS_ALLOWED_ORIGIN_PATTERNS:*}
