spring.activiti.cloud.services.notifications.graphql.ws.enabled=true
spring.sleuth.integration.patterns=!hystrixStreamOutput*,!channel*,!clientInboundChannel*,!clientOutboundChannel*,!brokerChannel*,*

spring.graphql.websocket.path=/v2/ws/graphql
spring.graphql.websocket.keep-alive=PT5S
