# enable deletion endpoints
activiti.rest.enable-deletion=true
# configure jackson Java Date format
spring.jackson.date-format=org.activiti.cloud.common.properties.StdDateFormatWithoutColonInTimeZone
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
