spring.cloud.stream.bindings.mtcResultsConsumer-in-0.destination=mtc-connector-reply-exchange
spring.cloud.stream.bindings.mtcResultsConsumer-in-0.contentType=application/json
spring.cloud.stream.bindings.mtcResultsConsumer-in-0.group=mtc-reply-${ACT_RB_APP_NAME:${spring.application.name}}

spring.cloud.stream.rabbit.bindings.mtcResultsConsumer-in-0.consumer.prefix=
spring.cloud.stream.rabbit.bindings.mtcResultsConsumer-in-0.consumer.queueNameGroupOnly=true
spring.cloud.stream.rabbit.bindings.mtcResultsConsumer-in-0.consumer.bindQueue=true
spring.cloud.stream.rabbit.bindings.mtcResultsConsumer-in-0.consumer.declareExchange=true
spring.cloud.stream.rabbit.bindings.mtcResultsConsumer-in-0.consumer.exchangeType=topic
