activiti.cloud.service.type=runtime-bundle
spring.activiti.deploymentMode=never-fail

spring.activiti.async-executor.default-async-job-acquire-wait-time-in-millis=5000
spring.activiti.async-executor.default-timer-job-acquire-wait-time-in-millis=5000

spring.activiti.process-definition-cache-name=processDefinitions
activiti.spring.cache-manager.caches.processDefinitions.caffeine.spec=maximumSize=${spring.activiti.process-definition-cache-limit:1000}, expireAfterAccess=10m, recordStats

#ensures that producer participates in the Spring transactions
spring.cloud.stream.rabbit.bindings.auditProducer.producer.transacted=${ACT_AUDIT_PRODUCER_TRANSACTED:true}
spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix=${ACT_AUDIT_PRODUCER_TRANSACTION_ID_PREFIX:tx-}

#disables zipkin reporting
spring.zipkin.enabled=false

#configured function router support for consumer bindings only
activiti.cloud.messaging.function-router.enabled=false
activiti.cloud.messaging.function-router.group=${spring.application.name}
activiti.cloud.messaging.function-router.routes.commandConsumer.enabled=true
activiti.cloud.messaging.function-router.routes.integrationErrorsConsumer.enabled=true
activiti.cloud.messaging.function-router.routes.integrationResultsConsumer.enabled=true
activiti.cloud.messaging.function-router.routes.connectorIncidentConsumer.enabled=true
activiti.cloud.messaging.function-router.routes.myCmdResults.enabled=true
activiti.cloud.messaging.function-router.routes.signalConsumer.enabled=true
activiti.cloud.messaging.function-router.routes.messageConnectorInput.enabled=true
activiti.cloud.messaging.function-router.routes.asyncExecutorJobsInput.enabled=true
activiti.cloud.messaging.function-router.routes.auditProducer.override-required-producer-groups=consumer
activiti.cloud.messaging.function-router.routes.auditProducerIncidents.override-required-producer-groups=consumer
