alter table process_definition
    add category varchar(255);

alter table task_variable modify id generated by default as identity;
alter table process_variable modify id generated by default as identity;
