CREATE SEQUENCE IF NOT EXISTS QUERY_INT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE TABLE IF NOT EXISTS QUERY_INT_CHANNEL_MESSAGE (
                                   MESSAGE_ID CHAR(36) NOT NULL,
                                   GROUP_KEY CHAR(36) NOT NULL,
                                   CREATED_DATE BIGINT NOT NULL,
                                   MESSAGE_PRIORITY BIGINT,
                                   MESSAGE_SEQUENCE BIGINT NOT NULL DEFAULT nextval('QUERY_INT_MESSAGE_SEQ'),
                                   MESSAGE_CONTENT JSONB,
                                   REGION VARCHAR(100) NOT NULL,
                                   constraint QUERY_INT_CHANNEL_MESSAGE_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);

CREATE INDEX IF NOT EXISTS QUERY_INT_CHANNEL_MSG_DELETE_IDX ON QUERY_INT_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_ID);
-- This is needed if the message group store property 'priorityEnabled' is true
CREATE UNIQUE INDEX IF NOT EXISTS QUERY_INT_CHANNEL_MSG_PRIORITY_IDX ON QUERY_INT_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_PRIORITY DESC NULLS LAST, CREATED_DATE, MESSAGE_SEQUENCE);
