CREATE SEQUENCE IF NOT EXISTS QUERY_INT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE IF NOT EXISTS QUERY_INT_CHANNEL_MESSAGE (
                                   MESSAGE_ID CHAR(36) NOT NULL,
                                   GROUP_KEY VARCHAR2(36) NOT NULL,
                                   CREATED_DATE NUMBER(19,0) NOT NULL,
                                   MESSAGE_PRIORITY NUMBER(19,0),
                                   MESSAGE_SEQUENCE NUMBER(19,0) NOT NULL ,
                                   MESSAGE_CONTENT JSON,
                                   REGION VARCHAR2(100) NOT NULL,
                                   constraint QUERY_INT_CHANNEL_MESSAGE_PK primary key (REGION, GROUP_KEY, CREATED_DATE, MESSAGE_SEQUENCE)
);

CREATE INDEX IF NOT EXISTS QUERY_INT_CHANNEL_MSG_DELETE_IDX ON QUERY_INT_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_ID);
-- This is needed if the message group store property 'priorityEnabled' is true
CREATE UNIQUE INDEX IF NOT EXISTS QUERY_INT_CHANNEL_MSG_PRIORITY_IDX ON QUERY_INT_CHANNEL_MESSAGE (REGION, GROUP_KEY, MESSAGE_PRIORITY DESC, CREATED_DATE, MESSAGE_SEQUENCE);
