DELETE INDEX IF EXISTS QUERY_INT_CHANNEL_MSG_DELETE_IDX;
DELETE INDEX IF EXISTS QUERY_INT_CHANNEL_MSG_PRIORITY_IDX;
DELETE TABLE IF EXISTS QUERY_INT_CHANNEL_MESSAGE;
DELETE SEQUENCE IF EXISTS QUERY_INT_MESSAGE_SEQ;
