DROP INDEX IF EXISTS QUERY_INT_CHANNEL_MSG_DELETE_IDX;
DROP INDEX IF EXISTS QUERY_INT_CHANNEL_MSG_PRIORITY_IDX;
DROP TABLE IF EXISTS QUERY_INT_CHANNEL_MESSAGE;
DROP SEQUENCE IF EXISTS QUERY_INT_MESSAGE_SEQ;
