create sequence audit_sequence start with 1 increment by 1;

create table audit_event
(
    type                       varchar(31) not null,
    id                         integer      not null,
    app_name                   varchar(255),
    app_version                varchar(255),
    business_key               varchar(255),
    entity_id                  varchar(255),
    event_id                   varchar(255),
    event_type                 varchar(255),
    message_id                 varchar(255),
    parent_process_instance_id varchar(255),
    process_definition_id      varchar(255),
    process_definition_key     varchar(255),
    process_instance_id        varchar(255),
    sequence_number            integer     not null,
    service_full_name          varchar(255),
    service_name               varchar(255),
    service_type               varchar(255),
    service_version            varchar(255),
    timestamp                  integer,
    bpmn_activity              CLOB,
    cause                      varchar(255),
    error                      CLOB,
    flow_node_id               varchar(255),
    integration_context_id     varchar(255),
    message                    CLOB,
    process_instance           CLOB,
    process_definition         CLOB,
    sequence_flow              CLOB,
    signal                     CLOB,
    task                       CLOB,
    task_id                    varchar(255),
    task_name                  varchar(255),
    candidate_group            CLOB,
    candidate_user             CLOB,
    timer                      CLOB,
    variable_instance          CLOB,
    variable_name              varchar(255),
    variable_type              varchar(255),
    message_subscription	   CLOB,
    primary key (id)
);
