name: Maven build (docker images)

on:
  workflow_call:
    inputs:
      matrix-json:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      BOT_GITHUB_TOKEN:
        required: true
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build:
    name: maven-build (${{ matrix.short-name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include: ${{ fromJSON(inputs.matrix-json) }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/maven-build@9f51752cb7845dce8e8b13b866c127681f418bb3 # v17.7.0
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        with:
          java-version: '25'
          java-distribution: 'corretto'
          reuse-testcontainers: 'true'
          maven-command: >-
            install -T 1C -Dskip.common.tests=true -DskipTests=true -DskipITs=true
            -pl ${{ matrix.extra-modules }}${{ matrix.path }} -am
          m2-current-build-upload-name: m2-${{ matrix.short-name }}
          target-folder-upload-name: target-${{ matrix.short-name }}
          m2-cache-exclusion-pattern: org/activiti
          uploaded-artifacts-retention-days: '1'
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image (${{ matrix.short-name }})
        if: matrix.skip-docker != 'true'
        shell: bash
        run: make "docker/${{ matrix.short-name }}"
