name: Maven test (docker images)

on:
  workflow_call:
    inputs:
      matrix-json:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      BOT_GITHUB_TOKEN:
        required: true
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true

jobs:
  test:
    name: maven-test (${{ matrix.short-name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.matrix-json) }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/maven-build@a8bc14631a9ce72275346e536607c4527591112a # v18.18.0
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        with:
          java-version: '25'
          java-distribution: 'corretto'
          reuse-testcontainers: 'true'
          maven-command: >-
            verify -Dskip.common.tests=true -Dmaven.install.skip=true -Dswagger.skip
            -pl ${{ matrix.extra-modules }}${{ matrix.path }} -am
            ${{ matrix.test-maven-flags }} -U
          jacoco-report-name: jacoco-${{ matrix.short-name }}
          target-folder-upload-name: target-test-${{ matrix.short-name }}
          m2-cache-exclusion-pattern: org/activiti
          uploaded-artifacts-retention-days: '1'
