name: Create Pre-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'

jobs:
  create-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Resolve activiti version
        id: resolve-versions
        run: |
          ACTIVITI_VERSION=$(yq -p=xml e '.project.properties."activiti.version"' activiti-cloud-api/pom.xml)
          ACTIVITI_CLOUD_VERSION=$(yq -p=xml e '.project.version' pom.xml)
          echo "activiti-tag=$ACTIVITI_VERSION" >> $GITHUB_OUTPUT
          echo "activiti-cloud-tag=$ACTIVITI_CLOUD_VERSION" >> $GITHUB_OUTPUT

      - run: touch release.yaml

      - uses: Alfresco/alfresco-build-tools/.github/actions/update-project-base-tag@a3f5a4ae53302e9a1f9dc728dee0f4069c1bc584 # v5.22.1
        with:
          release-descriptor: release.yaml
          project: activiti
          tag: ${{ steps.resolve-versions.outputs.activiti-tag }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/update-project-base-tag@a3f5a4ae53302e9a1f9dc728dee0f4069c1bc584 # v5.22.1
        with:
          release-descriptor: release.yaml
          project: activitiCloud
          tag: ${{ steps.resolve-versions.outputs.activiti-cloud-tag }}

      - name: Create prerelease
        env:
          TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          gh release create $TAG 'release.yaml#Release Descriptor' --prerelease -t $TAG
