name: "Dependency Graph Submission of Transitive Dependencies"

on:
  push:
    branches: ["develop"]
jobs:
  submit:
    name: Submit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 25
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: "25"
          distribution: "corretto"
      - name: Submit Dependency Graph
        uses: Alfresco/alfresco-build-tools/.github/actions/maven-dependency-scan@da99ab845e78301fcb0680d16cbc185a40a1938c # v18.24.1
        with:
          java-version: '25'
          maven-version: '3.9.9'
          maven-args: -Dmaven.wagon.http.pool=false
          maven-username: ${{ secrets.NEXUS_USERNAME }}
          maven-password: ${{ secrets.NEXUS_PASSWORD }}
