name: "PR Review check"

on:
  pull_request_review:
    types:
      - submitted
  pull_request:
    branches:
      - develop
    types:
      - labeled

jobs:
  check:
    uses: Alfresco/alfresco-build-tools/.github/workflows/pr-review-check.yml@ee10ec96d25c2cdfc6f45d3398aae1c6190f4d5d # v10.5.0
    with:
      trigger-labels: '["CI", "preview", "skip-tests"]'
      milestone-name: 'Validating'
    secrets:
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
