name: Versions propagation auto-merge
on:
  pull_request:
    types: [labeled]
    branches:
      - develop

jobs:
  versions-propagation-auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/automate-propagation@691c1d16c90c88a92d2438a001acdefc0efa7d2a # v8.26.0
      with:
        auto-merge-token: ${{ secrets.BOT_GITHUB_TOKEN }}
        approval-token: ${{ secrets.GITHUB_TOKEN }}
