activiti.cloud.messaging.function-router.routes.queryConsumer.enabled=${ACT_QUERY_CONSUMER_FUNCTION_ROUTER_ENABLED:false}

spring.cloud.stream.bindings.queryConsumer.consumer.partitioned=${activiti.cloud.messaging.partitioned}
spring.cloud.stream.bindings.queryConsumeril con=${ACT_QUERY_CONSUMER_CONCURRENCY:1}

spring.cloud.stream.rabbit.bindings.queryConsumer.consumer.prefetch=${ACT_QUERY_CONSUMER_RABBIT_PREFETCH:20}

spring.cloud.stream.instanceIndex=${activiti.cloud.messaging.instance-index}
spring.cloud.stream.instanceCount=${activiti.cloud.messaging.partition-count}
spring.cloud.stream.bindings.queryConsumer.consumer.instanceIndexList=${ACT_QUERY_CONSUMER_INSTANCE_INDEX_LIST:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}

spring.jackson.mapper.default-view-inclusion=true
